apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default #managed-premium para premium
  resources:
    requests:
      storage: 1Gi # 1gb de almacenamiento
