apiVersion: v1
kind: Service
metadata:
  name: clusterip-nginx
spec:
  selector:
    app: nginx
  ports:
    # Por defecto y por comodidad, el `TargetPort` tiene el mismo valor que el campo `port.
    - port: 80
      targetPort: 80