apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sfs
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        # args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        - name: MYSQL_ROOT_HOST
          value: "%"
        - name: MYSQL_DATABASE
          value: "symfonydb"
        - name: MYSQL_USER
          value: "symfony"
        - name: MYSQL_PASSWORD
          value: "symfony"

        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: volume-db
      volumes:
        - name: volume-db
          persistentVolumeClaim:
            claimName: pvc-db