apiVersion: v1
kind: Service
metadata:
  name: clusterip-mysql
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    # Por defecto y por comodidad, el `TargetPort` tiene el mismo valor que el campo `port.
    port: 3306
    targetPort: 3306