apiVersion: v1
kind: Service
metadata:
  name: clusterip-phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    # Por defecto y por comodidad, el `TargetPort` tiene el mismo valor que el campo `port.
    - port: 8080
      targetPort: 80