apiVersion: v1
kind: Service	
metadata:
  name: phpmyadmin-loadbalancer-svc
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
