apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-disk
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default #managed-premium para premium
  resources:
    requests:
      storage: 5Gi # 1gb de almacenamiento