apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - name: jnlp
      port: 50000
      targetPort: 50000
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: jenkins