apiVersion: v1
kind: Service	
metadata:
  name: jenkins-loadbalancer-svc
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
