apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default #managed-premium para premium
  resources:
    requests:
      storage: 5Gi
