apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: pruebascurso.azurecr.io/finalcurso-nginx:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www"
          name: volume-www
      volumes:
        - name: volume-www
          persistentVolumeClaim:
            claimName: www-disk